# ---------------- Fonts ----------------
font_family JetBrainsMono Nerd Font
bold_font JetBrainsMono Nerd Font
italic_font JetBrainsMono Nerd Font
bold_italic_font JetBrainsMono Nerd Font

font_size 12
force_ltr no
disable_ligatures always

# ---------------- Scrollback ----------------
scrollback_lines 4096

# ---------------- Cursor ----------------
cursor_shape beam
cursor_beam_thickness 2

# ---------------- Mouse / UX ----------------
url_style straight
detect_urls yes
open_url_with default
copy_on_select no

# ---------------- Window behavior ----------------
remember_window_size no
initial_window_width 785
initial_window_height 450
window_padding_width 10

# ---------------- Visual ----------------
background_opacity 0.8

# ---------------- Remote control ----------------
allow_remote_control no

# ---------------- Disable close confirmation ----------------
confirm_os_window_close -1

# ---------------- Theme includes ----------------
include ~/.config/kitty/dank-theme.conf
include ~/.config/kitty/dank-tabs.conf

# ---------------- Window Navigation ----------------
map ctrl+right next_window
map ctrl+left previous_window
map ctrl+up move_window_forward
map ctrl+down move_window_backward

# ---------------- Default Layout ----------------
enabled_layouts grid
