creation_rules:
  - path_regex: secrets/raspi/.*\.yaml$
    age: age1fw3uyseudkjxakh67v03f8qn2jqsa05rzds8h9yvckvph2e78e5q0fqpka
  - path_regex: secrets/laptop-amd64/.*\.yaml$
    age: age13st2ctgtlkrk6084hvk4dfjl5cgy4zzhha6zvk6w7009gqwp75qqyf8nen