creation_rules:
  - path_regex: secrets/.*\.yaml$
    age: >-
      age1ad5dr2mkccymy6m7v25m5ykd6s50ssv4jmgy48ee2nhtlggmkszs4t5uf6,
      age1fw3uyseudkjxakh67v03f8qn2jqsa05rzds8h9yvckvph2e78e5q0fqpka
