# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
# yada yada yada. fuck you! edit this all u want
{ config, lib, pkgs, ... }:

{


  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "rtsx_usb_sdmmc" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.kernelParams = [ 
    
    # For some reason you cannot 'nixos-rebuild switch' without this...
    "systemd.gpt_auto=no"

    # disable password timeout for luks devices
    "luks.options=timeout=0"
    "rd.luks.options=timeout=0"

    # assume root device is already there
    # do not wait for it to appear
    "rootflags=x-systemd.device-timeout=0"

    # nvme speedup
    "nvme_core.default_ps_max_latency_us=0"
  ];

  fileSystems."/" =
    { device = "/dev/mapper/nixosroot";
      fsType = "xfs";
    };

  boot.initrd.luks.devices."nixosroot".device = "/dev/disk/by-uuid/778cb3cd-345c-4920-ad23-93ea93d5b278";
  boot.initrd.luks.devices."nixosroot".preLVM = true; 

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/05FA-F4DC";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/mapper/nixoshome";
      fsType = "xfs";
    };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # hostname
  networking.hostName = "nixosaurus";

  environment.etc."crypttab".text = ''
    nixoshome UUID=55628a09-46ca-4299-9b40-f9cf45395d16 /root/secrets/homeluks.key luks,nofail
  '';
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };

}
